{
 "title": "Kuberntes",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_deployment_status_replicas_available, namespace)"
    }
   },
   {
    "name": "deployment",
    "query": {
     "query": "label_values(kube_deployment_status_replicas_available{namespace=\"default\"}, deployment)"
    }
   },
   {
    "name": "service_app_filter",
    "query": {
     "query": "label_values(nginx_ingress_controller_upstream_server_response_latency_ms_count{namespace=\"nginx-ingress\", upstream=~\".*-(foo|bar)-service-9898\"}, upstream)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "number of WN",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 1, "y": 0 },
   "targets": [
    {
     "expr": "sum(\r\n  avg_over_time(\r\n    kube_node_status_condition{\r\n      condition=\"Ready\",\r\n      status=\"true\"\r\n    }[$__rate_interval]\r\n  )\r\n) - 1\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "number of pods",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(\r\n  avg_over_time(\r\n    kube_deployment_status_replicas_available{\r\n      namespace=\"default\",\r\n      deployment=~\"(foo|bar)-app\"\r\n    }[$__rate_interval]\r\n  ),\r\n  \"service_name\",\r\n  \"$1-app\",\r\n  \"deployment\",\r\n  \"(foo|bar)-app\"\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taxa de Chegada por Serviço",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 1, "y": 7 },
   "targets": [
    {
     "expr": "label_replace(\r\n  sum by (upstream) (\r\n    rate(nginx_ingress_controller_upstream_server_response_latency_ms_count{\r\n      namespace=\"nginx-ingress\",\r\n      upstream=~\"default-example-ingress-.*\\\\.amazonaws\\\\.com-(foo|bar)-service-9898\"\r\n    }[$__rate_interval])\r\n  ),\r\n  \"service_name\",\r\n  \"$1-app\",\r\n  \"upstream\",\r\n  \"default-example-ingress-.*\\\\.amazonaws\\\\.com-(foo|bar)-service-9898\"\r\n)\r\nor\r\nlabel_replace(\r\n  avg(\r\n    sum by (upstream) (\r\n      rate(nginx_ingress_controller_upstream_server_response_latency_ms_count{\r\n        namespace=\"nginx-ingress\",\r\n        upstream=~\"default-example-ingress-.*\\\\.amazonaws\\\\.com-(foo|bar)-service-9898\"\r\n      }[$__rate_interval])\r\n    )\r\n  ) by (),\r\n  \"service_name\",\r\n  \"avg-arrival\",\r\n  \"upstream\",\r\n  \".*\"\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TP",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 10, "y": 7 },
   "targets": [
    {
     "expr": "label_replace(\r\n  sum by (upstream) (\r\n    rate(nginx_ingress_controller_upstream_server_response_latency_ms_count{\r\n      namespace=\"nginx-ingress\",\r\n      upstream=~\"default-example-ingress-.*\\\\.amazonaws\\\\.com-${service_app_filter}-service-9898\"\r\n    }[$__rate_interval])\r\n  ),\r\n  \"service_name\",\r\n  \"${service_app_filter}-app\",\r\n  \"upstream\",\r\n  \".*\"\r\n)\r\nor\r\nlabel_replace(\r\n  avg(\r\n    sum by (upstream) (\r\n      rate(nginx_ingress_controller_upstream_server_response_latency_ms_count{\r\n        namespace=\"nginx-ingress\",\r\n        upstream=~\"default-example-ingress-.*\\\\.amazonaws\\\\.com-(foo|bar)-service-9898\"\r\n      }[$__rate_interval])\r\n    )\r\n  ) by (),\r\n  \"service_name\",\r\n  \"avg-throughput\",\r\n  \"upstream\",\r\n  \".*\"\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 1, "y": 14 },
   "targets": [
    {
     "expr": "label_replace(\r\n  (\r\n    sum by (upstream) (\r\n      rate(nginx_ingress_controller_upstream_server_response_latency_ms_sum{\r\n        namespace=\"nginx-ingress\",\r\n        upstream=~\"default-example-ingress-.*\\\\.amazonaws\\\\.com-(foo|bar)-service-9898\"\r\n      }[$__rate_interval])\r\n    )\r\n    /\r\n    sum by (upstream) (\r\n      rate(nginx_ingress_controller_upstream_server_response_latency_ms_count{\r\n        namespace=\"nginx-ingress\",\r\n        upstream=~\"default-example-ingress-.*\\\\.amazonaws\\\\.com-(foo|bar)-service-9898\"\r\n      }[$__rate_interval])\r\n    )\r\n  ) / 1000,\r\n  \"service_name\",\r\n  \"$1-app\",\r\n  \"upstream\",\r\n  \"default-example-ingress-.*\\\\.amazonaws\\\\.com-(foo|bar)-service-9898\"\r\n)\r\nor\r\nlabel_replace(\r\n  avg(\r\n    (\r\n      sum by (upstream) (\r\n        rate(nginx_ingress_controller_upstream_server_response_latency_ms_sum{\r\n          namespace=\"nginx-ingress\",\r\n          upstream=~\"default-example-ingress-.*\\\\.amazonaws\\\\.com-(foo|bar)-service-9898\"\r\n        }[$__rate_interval])\r\n      )\r\n      /\r\n      sum by (upstream) (\r\n        rate(nginx_ingress_controller_upstream_server_response_latency_ms_count{\r\n          namespace=\"nginx-ingress\",\r\n          upstream=~\"default-example-ingress-.*\\\\.amazonaws\\\\.com-(foo|bar)-service-9898\"\r\n        }[$__rate_interval])\r\n      )\r\n    ) / 1000\r\n  ) by (),\r\n  \"service_name\",\r\n  \"avg-response\",\r\n  \"upstream\",\r\n  \".*\"\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cpu_usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 10, "y": 14 },
   "targets": [
    {
     "expr": "sum by (deployment_name) (\r\n  label_replace(\r\n    rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"${deployment}.*\", container=~\"$deployment\"}[$__interval]),\r\n    \"deployment_name\",\r\n    \"$1\",\r\n    \"pod\",\r\n    \"^([a-zA-Z0-9-]+)-[a-f0-9]{10}-[a-zA-Z0-9]{5}$\"\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "memory_usage_bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 1, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (deployment_name) (\r\n  label_replace(\r\n    avg_over_time(\r\n      container_memory_usage_bytes{\r\n        namespace=\"$namespace\",\r\n        pod=~\"$deployment.*\",\r\n        container!=\"\",\r\n        image!=\"\"\r\n      }[$__rate_interval]\r\n    ),\r\n    \"deployment_name\",\r\n    \"$1\",\r\n    \"pod\",\r\n    \"^(.+)-[a-z0-9]{1,}-[a-z0-9]{1,}$\"\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}