AWSTemplateFormatVersion: '2010-09-09'
Description: Criação da LabRole com permissões amplas.

Resources:
  LabRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LabRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
                - lambda.amazonaws.com
                - cloudformation.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

Outputs:
  LabRoleArn:
    Description: ARN da função LabRole
    Value: !GetAtt LabRole.Arn


#  aws cloudformation create-stack \
#  --stack-name LabRoleStack \
#  --template-body file://setup_cloudformation.yaml \
#  --capabilities CAPABILITY_NAMED_IAM